### ISSUE TITLE
NCH software

### ISSUE THREAD

**Issue by pidus** [DRSDavidSoft/additional-hosts#5]
Please add NCH software blocklist: `0.0.0.0 secure.nch.com.au`

**Comment by DRSDavidSoft** [comment]
@pidus interesting, I have seen this domain in some lists, so I will also add it to mine.  I hadn't done this before since none of my devices generated it.

### Reason for block:
 - [NCH Software](https://www.nchsoftware.com/) is an Australian software company with shady business practices that provides software for audio, video, graphics, and other media editing utilities.
- They have a history of bundling unwanted bloatware, preventing the user from uninstalling their software once installed, and are known as trojan/adware.

Thanks for reporting this domain!
